name: wev-awsmfa

on:  # yamllint disable-line rule:truthy
  - push

jobs:

  build:
    container: cariad/ci:1.0.0
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Sync dependencies
        run: pipenv sync --dev

      - name: Test
        run: pipenv run ./test.sh

      - name: Version
        run: echo "${GITHUB_REF##*/}" > wev_awsmfa/VERSION

      - name: Build
        run: pipenv run ./build.sh

      - name: Archive distributable
        uses: actions/upload-artifact@v2
        with:
          name: distributable
          path: dist
          retention-days: 1

  publish:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

      - name: Create distributable directory
        run: |
          mkdir dist
          cp *.whl dist
          ls -al dist/

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
